name: Daily Commit


on:
  schedule:
    - cron: '0 0 * * *' # Runs at midnight every day


jobs:
  make_commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Make a commit
      run: |
        git config --global user.name 'Venkatakrishnan-Ramesh'
        git config --global user.email 'venkatkrishnan2003@gmail.com'
        date > commit.txt
        git add .
        git commit -m "Updated"
        git push
